apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: gingersnap-operator
build:
  local:
    push: true
  artifacts:
  - image: operator
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - config/skaffold