---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gingersnap-project-io-v1alpha1-cache
  failurePolicy: Fail
  name: mcache.kb.io
  rules:
  - apiGroups:
    - gingersnap-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - caches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gingersnap-project-io-v1alpha1-eagercacherule
  failurePolicy: Fail
  name: meagercacherule.kb.io
  rules:
  - apiGroups:
    - gingersnap-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eagercacherules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gingersnap-project-io-v1alpha1-lazycacherule
  failurePolicy: Fail
  name: mlazycacherule.gingersnap-project.io
  rules:
  - apiGroups:
    - gingersnap-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lazycacherules
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gingersnap-project-io-v1alpha1-cache
  failurePolicy: Fail
  name: vcache.kb.io
  rules:
  - apiGroups:
    - gingersnap-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - caches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gingersnap-project-io-v1alpha1-eagercacherule
  failurePolicy: Fail
  name: veagercacherule.kb.io
  rules:
  - apiGroups:
    - gingersnap-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eagercacherules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gingersnap-project-io-v1alpha1-lazycacherule
  failurePolicy: Fail
  name: vlazycacherule.gingersnap-project.io
  rules:
  - apiGroups:
    - gingersnap-project.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lazycacherules
  sideEffects: None
