# permissions for end users to edit eagercacherules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eagercacherule-editor-role
rules:
- apiGroups:
  - gingersnap-project.io
  resources:
  - eagercacherules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gingersnap-project.io
  resources:
  - eagercacherules/status
  verbs:
  - get
