# permissions for end users to view lazycacherules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lazycacherule-viewer-role
rules:
- apiGroups:
  - gingersnap-project.io
  resources:
  - lazycacherules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gingersnap-project.io
  resources:
  - lazycacherules/status
  verbs:
  - get
