# permissions for end users to edit lazycacherules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lazycacherule-editor-role
rules:
- apiGroups:
  - gingersnap-project.io
  resources:
  - lazycacherules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gingersnap-project.io
  resources:
  - lazycacherules/status
  verbs:
  - get
