apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: gingersnap-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CacheRegion is the Schema for the cacheregions API
      displayName: Cache Region
      kind: CacheRegion
      name: cacheregions.gingersnap-project.io
      version: v1alpha1
    - description: Cache is the Schema for the caches API
      displayName: Cache
      kind: Cache
      name: caches.gingersnap-project.io
      version: v1alpha1
  description: Memory Service
  displayName: gingersnap Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cache
  - caching
  links:
  - name: Gingersnap Operator
    url: https://gingersnap-project.io
  maintainers:
  - email: infinispan-dev@lists.jboss.org
    name: Infinispan Community
  maturity: alpha
  provider:
    name: Gingersnap
  version: 0.0.0
