apiVersion: gingersnap-project.io/v1alpha1
kind: EagerCacheRule
metadata:
  name: eagercacherule-sample
spec:
  cacheRef:
    name: cache-sample
    namespace: default
  tableName: table
  key:
    keyColumns:
      - "col1"
