bases:
  - ../default

# Define permissions at the cluster scope so that we can watch any namespace with Skaffold
patches:
  - manager.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: manager-role
    patch: |-
      - op: replace
        path: /kind
        value: ClusterRole
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: manager-rolebinding
    patch: |-
      - op: replace
        path: /roleRef/kind
        value: ClusterRole
