name: Publish to main 
on:
  schedule:
    - cron:  '*0 * * * *'    # At every 0th minute
  
  
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 
  release-version: "0.0.1"
  replace_version: "0.0.0"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"

      - name: Checkout
        uses: actions/checkout@v2
        with: 
           path: operator

      - name: Check if the image exists
        run:  |
          docker manifest inspect quay.io/operatorhubio/gingersnap:v${{ env.release-version}} > /dev/null

      - name: Update CSV file to Next version and Push to main 
        if: success()
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'config/manifests/bases/*-operator.clusterserviceversion.yaml'
          branch: main
          message: 'Next Version ${{ env.release-ersion }}' 
          commitUserName: 'infinispan-qe-bot'
          commitUserEmail: 'q*@infinispan.org'
          token: ${{ secrets.PAT_TOKEN }}   
          changes: |
            {
              "replaces": "gingersnap-operator.v${{ env.replace_version }}"
            }
          