name: Post Release - Update CSV
on:
  schedule:
    - cron: '*/30 * * * *'    # At every 30th minute
    
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "infinispan-qe-bot"
          git config --global user.email "q*@infinispan.org"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if the image exists
        run:  |
          docker manifest inspect quay.io/operatorhubio/gingersnap:v${{ env.release-version}} > /dev/null

      - name: Update CSV file to Next version and Push to main 
        if: ${{ success() && inputs.prev_version }}
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'config/manifests/bases/gingersnap-operator.clusterserviceversion.yaml'
          branch: main
          message: 'Next Version ${{ env.release-version }}'
          commitUserName: 'infinispan-qe-bot'
          commitUserEmail: 'q*@infinispan.org'
          token: ${{ secrets.PAT_TOKEN }}   
          changes: |
            {
              "spec.replaces": "gingersnap.v${{ env.replace_version }}"
            }

      - name: Remove scheduled job 
        uses: cardinalby/unschedule-job-action@v1
        if: success()
        with:
          ghToken: ${{ secrets.PAT_TOKEN }} 
          deleteRefTag: false
          