name: Image Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The Operator branch/tag to checkout when creating the image."
        required: true
        default: "release_operator_image"
      tags:
        description: "The Operator version to build."
        required: true
        default: "1.0.0" 


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.PRIVATE_QUAY_TOKEN }}
          password: ${{ secrets.PRIVATE_QUAY_USERNAME}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/pminz/operator-images:${{ github.event.inputs.tags }}
          build-args: |
            OPERATOR_VERSION=${{ github.event.inputs.tags }}