name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  TEST_OUTPUT_DIR: ${{ github.workspace }}/test/reports

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init variables action variables
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      # Cache local bin dependencies
      - name: Bin Cache
        uses: actions/cache@v2
        with:
          path: bin
          key: ${{ runner.os }}-bin-${{ hashFiles('Makefile') }}

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --enable bodyclose,gofmt,unconvert,whitespace --timeout 3m0s --verbose
          version: v1.46.2

      - name: Unit Tests
        run: make test

      - name: Check for unstaged changes
        run: git diff --name-only --exit-code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Operator SDK
        run: |
          curl -L https://github.com/operator-framework/operator-sdk/releases/download/v1.22.2/operator-sdk_linux_amd64 -o operator-sdk
          chmod +x operator-sdk
          sudo mv operator-sdk /bin/

      - name: Install Kind
        run: go install sigs.k8s.io/kind@v0.14.0

      - name: Create Kind Cluster
        run: ./hack/kind.sh

      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
          restore-keys: |
            fixed-${{ github.sha }}
            fixed-

      - name: Build and Deploy Operator with Skaffold
        uses: hiberbee/github-action-skaffold@1.18.0
        with:
          command: run

      - name: E2E Integration tests
        run: make test-e2e

      - name: Test Logs
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: ${{ env.TEST_OUTPUT_DIR }}
